#%RAML 1.0
title: Example API Documentation

description: |
  Markdown description example.

documentation:
 - title: Home
   content: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec commodo leo. Sed ut malesuada enim. Interdum et malesuada
    fames ac ante ipsum primis in faucibus. Phasellus viverra interdum vulputate. Morbi eleifend congue aliquam. Vestibulum ante
    ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt pellentesque dui vel hendrerit.
    Vestibulum egestas a risus varius faucibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos
    himenaeos. Duis dui turpis, finibus ut tempor ac, condimentum eget lectus. Praesent in diam tempus, sagittis leo ac, porta ex.
    Aliquam id mollis nulla. Nam eu mattis ligula, vel mollis turpis. Integer augue orci, ullamcorper vel pellentesque sit amet,
    auctor vel sapien. Maecenas dignissim, lectus eu sodales porta, arcu mi fringilla erat, at aliquam metus ligula vel mi. Nunc
    laoreet arcu nisl, sit amet facilisis nunc luctus non.